### ISSUE TITLE
Math Magicians: refactor with hooks

### ISSUE THREAD

**Issue by hansderly** [hansderly/math-magicians#4]
Hi 👋,
This is how i used hook inside of that project.

In React, a hook is a function that allows you to use React state and other React features in functional components. The most commonly used hooks are useState, useEffect, useContext, and useReducer.

In this project i only use `useState` hook

Here's a brief explanation of how it works:
useState allows you to add state to a functional component. You can use it to create and update state variables that trigger a re-render of the component when they change.

You can declare a state by using this syntax:

```
const [result, setResult] = useState(0);
```

And after you can update the state of that variable, in that case `result`, by invoke the setResult function provided by the `useState` hook, like that:

```
  const handleClick = (e) => {
    setResult((prevState) => calculate(prevState, e.target.innerText));
  };
```
Thanks.

**Comment by omarsalem7** [comment]
Hi @hansderly 😊, 
# STATUS: APPROVED! 🥇 💯 

![giphy](https://media.giphy.com/media/n5VaQoW39Z9S0/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
✅ Project has met all the technical aspects you needed for this project. Keep rocking! 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
